### ISSUE TITLE
harbor-container-registry-1.4.1-build.1.tgz failed at Extracting release archive failed

### ISSUE THREAD

**Issue by alansbb** [pivotal-cf/docs-vmware-harbor#16]
After click apply changes during install harbor container registry 1.4.1, it stopped at "updating runtime configs for harbor-container-registry" with following error messages:
===== 2018-05-06 03:28:56 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=192.168.8.220 upload-release /var/tempest/releases/harbor-container-registry-1.4.1-build.1.tgz" Using environment '192.168.8.220' as client 'ops_manager' 0.00% 0.44% 17.75 MB/s 50s 

Task 181 Task 181 | 04:01:10 | Extracting release: Extracting release (00:00:15) L Error: Extracting release archive failed. Check task debug log for details. Task 181 | 04:01:25 |
 Error: Extracting release archive failed. Check task debug log for details. Task 181 Started Sun May 6 04:01:10 UTC 2018 Task 181 Finished Sun May 6 04:01:25 UTC 2018 Task 181 Duration 00:00:15 Task 181 error Uploading release file: Expected task '181' to succeed but state is 'error' Exit code 1

**Comment by alansbb** [comment]
Thanks for the update.

**Comment by animatedmax** [comment]
Closing ancient issue
