### ISSUE TITLE
Note known issue:  Add registry to default no_proxy hosts for Clair

### ISSUE THREAD

**Issue by kroberts7** [pivotal-cf/docs-vmware-harbor#34]
Operators are hitting the following known issue, fixed in OSS Harbor v1.6.1.  Can we note the workaround, pending targeted inclusion into CFF Bosh Harbor release?

Summary:
When proxy is set for Clair, there may be issue when Clair pulls image
from the registry if the `no_proxy` attribute is not updated.

Example error:
error: Unexpected status code: 400, text: {"Error":{"Message":"could not find layer"}}

Workaround details:

In VMware Harbor Registry > Clair Settings > No Proxy
Change From:
127.0.0.1,localhost,ui

Change To:
127.0.0.1,localhost,ui,registry

**Comment by lparis** [comment]
Thanks for reporting this. See https://github.com/pivotal-cf/docs-vmware-harbor/pull/35.

**Comment by bentarnoff** [comment]
Closing because this appears to be addressed. Thank you @kroberts7 @lparis !
